ViewModels/SignInViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ProjectVaila.ViewModels
{
	public class SignInViewModel
	{
		[Required(AllowEmptyStrings = false, ErrorMessage = "Введите корректный Email")]
		[Display(Name = "Email")]
		public string Email { get; set; }

		[Required(AllowEmptyStrings = false, ErrorMessage = "Введите пароль")]
		[DataType(DataType.Password)]
		[Display(Name = "Пароль")]
		public string Password { get; set; }

		[Display(Name = "Запомнить?")]
		public bool RememberMe { get; set; }
	}
}

Controllers/Account/SignInController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ProjectVaila.Providers.EFCoreProvider.Data;
using ProjectVaila.ViewModels;

namespace ProjectVaila.Controllers.Account
{
	public class SignInController : Controller
	{
		private readonly UserManager<IdentityUserContext> _userManager;
		private readonly SignInManager<IdentityUserContext> _signInManager;

		public SignInController(UserManager<IdentityUserContext> userManager, SignInManager<IdentityUserContext> signInManager)
		{
			_userManager = userManager;
			_signInManager = signInManager;
		}

		[HttpGet]
		public IActionResult Index()
		{
			ViewBag.PageTitle = "Sign In";
			ViewBag.DisplayHeader = false;

			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Index(SignInViewModel model)
		{
			ViewBag.PageTitle = "Sign In";
			ViewBag.DisplayHeader = false;

			if (!ModelState.IsValid) return View(model);

			var user = await _userManager.FindByEmailAsync(model.Email);

			if (user is not null)
			{
				var result =
					await _signInManager.PasswordSignInAsync(user.UserName, model.Password, model.RememberMe, false);

				if (result.Succeeded)
				{
					return RedirectToAction("Index", "Home");
				}
			}

			ModelState.AddModelError("", "Неправильный email и (или) пароль");

			return View(model);
		}
	}
}

Controllers/Account/SignUpController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using ProjectVaila.Providers.EFCoreProvider;
using ProjectVaila.Providers.EFCoreProvider.Data;
using ProjectVaila.ViewModels;

namespace ProjectVaila.Controllers.Account
{
	public class SignUpController : Controller
	{
		private readonly UserManager<IdentityUserContext> _userManager;
		private readonly SignInManager<IdentityUserContext> _signInManager;
		private readonly AppDbContext _appDbContext;

		public SignUpController(UserManager<IdentityUserContext> userManager, SignInManager<IdentityUserContext> signInManager, AppDbContext appDbContext)
		{
			_userManager = userManager;
			_signInManager = signInManager;
			_appDbContext = appDbContext;
		}

		[HttpGet]
		public IActionResult Index()
		{
			ViewBag.PageTitle = "Sign Up";
			ViewBag.DisplayHeader = false;

			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Index(SignUpViewModel model)
		{
			ViewBag.PageTitle = "Sign Up";
			ViewBag.DisplayHeader = false;

			if (!ModelState.IsValid) return View(model);

			var identityUser = new IdentityUserContext
			{
				UserName = model.Email,
				Email = model.Email,
			};
				
			var addUserResult = await _userManager.CreateAsync(identityUser, model.Password);

			if (addUserResult.Succeeded)
			{
				await _signInManager.SignInAsync(identityUser, false);

				var identityUserContext = await _userManager.FindByEmailAsync(model.Email);

				var user = new User()
				{
					Id = identityUserContext.Id,
					FirstName = model.FirstName,
					LastName = model.LastName,
				};

				await _appDbContext.AddAsync(user);
				
				return RedirectToAction("Index", "Home");
			}

			foreach (var error in addUserResult.Errors)
			{
				string errorDesc = error.Description;

				//todo: разобраться как заменить switch на более лакончиный код
				switch (error.Code)
				{
					case "PasswordTooShort":
						errorDesc = "Пароль должен содержать как минимум 6 символов";
						break;
					case "PasswordRequiresNonAlphanumeric":
						errorDesc = "Пароль должен содержать как минимум один символ не являющийся цифробуквенным";
						break;
					case "PasswordRequiresLower":
						errorDesc = "Пароль должен содержать как минимум один символ в нижнем регистре ";
						break;
					case "PasswordRequiresUpper":
						errorDesc = "Пароль должен содержать как минимум один символ в верхнем регистре ";
						break;
				}

				ModelState.AddModelError(string.Empty, errorDesc);
			}

			return View(model);
		}
	}
}

Views/SignIn/Index.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model ProjectVaila.ViewModels.SignInViewModel

<link rel="stylesheet" href="~/css/SignInAndSignUp.css">

<form class="form-signin m-auto w-100 text-center" method="post" asp-controller="SignIn" asp-action="Index">
	<a href="/Home/Index"><img class="mb-4" src="~/icons/logos/vailaLogo.png" alt="" height="57"></a>
	<h1 class="h3 mb-3 fw-normal text-black-50">Авторизация</h1>
	@if (ViewData.ModelState.ErrorCount > 0)
	{
		<div class="alert alert-dismissible alert-info fade show" role="alert">
			<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
			<strong>Ошибка входа</strong>
			@foreach (var errors in ViewData.ModelState.Values)
			{
				<ul>
				@foreach (var error in errors.Errors)
				{
					<li>@error.ErrorMessage</li>
				}
				</ul>
			}
		</div>
	}
	<div class="form-floating col-12">
		<input type="text" asp-for="Email" name="Email" class="form-control start-input" id="floatingInput" placeholder="name@example.com">
		<label asp-for="Email" for="floatingInput">Email адрес или номер телефона</label>
	</div>
	<div class="form-floating col-12">
		<input type="password" asp-for="Password" name="Password" class="form-control end-input" id="floatingPassword" placeholder="Password">
		<label asp-for="Password" for="floatingPassword">Пароль</label>
	</div>

	<div class="checkbox mb-3">
		<label asp-for="RememberMe" class="text-black">
			<input asp-for="RememberMe" type="checkbox" value="remember-me"> Запомнить меня
		</label>
	</div>
	<button class="w-100 btn btn-lg mb-3" type="submit" style="background-color: #65D4EB; color: aliceblue;">Войти</button>
	<button class="w-100 btn btn-lg" type="button" style="background-color: #65D4EB; color: aliceblue;"onclick="location.href='@Url.Action("Index", "SignUp")'">Создать аккаунт</button>
	<p class="mt-5 mb-3 text-muted">Vaila company &copy; 2023</p>
</form>